// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQbkrBV1uXeIfcqgY6qpvzSlMSsozOh4',
    appId: '1:930070024045:web:28ac4cd4ceffa85ff1d464',
    messagingSenderId: '930070024045',
    projectId: 'personal-focus-app',
    authDomain: 'personal-focus-app.firebaseapp.com',
    storageBucket: 'personal-focus-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DJrKFLUQYjHoDzv6ucwl4aHFrU125TE',
    appId: '1:930070024045:android:ad2e4276f92b5012f1d464',
    messagingSenderId: '930070024045',
    projectId: 'personal-focus-app',
    storageBucket: 'personal-focus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5CAIFSnFQwCVEzIUZ-p6qLb4bz0muvA',
    appId: '1:930070024045:ios:48da397936537fdff1d464',
    messagingSenderId: '930070024045',
    projectId: 'personal-focus-app',
    storageBucket: 'personal-focus-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5CAIFSnFQwCVEzIUZ-p6qLb4bz0muvA',
    appId: '1:930070024045:ios:48da397936537fdff1d464',
    messagingSenderId: '930070024045',
    projectId: 'personal-focus-app',
    storageBucket: 'personal-focus-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASQbkrBV1uXeIfcqgY6qpvzSlMSsozOh4',
    appId: '1:930070024045:web:e3789912212a26dbf1d464',
    messagingSenderId: '930070024045',
    projectId: 'personal-focus-app',
    authDomain: 'personal-focus-app.firebaseapp.com',
    storageBucket: 'personal-focus-app.firebasestorage.app',
  );
}
