// lib/main.dart
// ignore_for_file: avoid_print

import 'dart:async'; // Needed for StreamSubscription

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// Import your generated Firebase options
import 'package:flutter_application_1/firebase_options.dart';

// Import your custom models and repository
import 'package:flutter_application_1/focus_session.dart'; // Make sure this path is correct
import 'package:flutter_application_1/daily_focus_repository.dart'; // Make sure this path is correct

// Declare a global instance of your repository for easy access.
// In larger apps, consider using state management solutions like Provider or Riverpod
// for better dependency injection.
late final DailyFocusRepository dailyFocusRepository;

void main() async {
  // Ensure that Flutter binding is initialized.
  // This is crucial before calling any native code, like Firebase.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the platform-specific options generated by FlutterFire CLI.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  try {
    // Attempt to sign in anonymously. If already signed in (e.g., from a previous session),
    // it will reuse the existing anonymous user.
    UserCredential userCredential = await FirebaseAuth.instance.signInAnonymously();
    print("Signed in anonymously with UID: ${userCredential.user?.uid}");
  } on FirebaseAuthException catch (e) {
    switch (e.code) {
      case 'operation-not-allowed':
        print("Anonymous sign-in hasn't been enabled for this project.");
        // This is the error if you haven't enabled it in Firebase Console!
        break;
      default:
        print("Unknown error during anonymous sign-in: $e");
    }
  }
  // Get the Firestore instance AFTER Firebase has been initialized.
  final FirebaseFirestore db = FirebaseFirestore.instance;

  // Initialize your DailyFocusRepository, passing the Firestore instance.
  dailyFocusRepository = DailyFocusRepository(db);

  // Run your Flutter application.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Personal Focus App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(), // Your main home screen widget
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _statusMessage = 'App Started. Waiting for data...';
  List<FocusSession> _todaySessions = [];
  StreamSubscription<List<FocusSession>>? _sessionSubscription; // To manage the real-time listener

  @override
  void initState() {
    super.initState();
    // Start listening to today's focus sessions as soon as the widget initializes.
    _listenToTodaySessions();
  }

  void _listenToTodaySessions() {
    // Access the global dailyFocusRepository instance
    _sessionSubscription = dailyFocusRepository.getTodayFocusSessions().listen((sessions) {
      setState(() {
        _todaySessions = sessions;
        _statusMessage = 'Loaded ${sessions.length} sessions for today.';
      });
    }, onError: (error) {
      setState(() {
        _statusMessage = 'Error loading sessions: $error';
      });
    });
  }

  Future<void> _addRandomFocusSession() async {
    setState(() {
      _statusMessage = 'Adding new session...';
    });
    try {
      // Simulate adding a session with random seconds and a simple tag
      final int randomSeconds = (DateTime.now().minute % 30 + 1) * 60; // 1-30 minutes
      final String randomTag = ['Work', 'Study', 'Personal', 'Break'][DateTime.now().second % 4];

      await dailyFocusRepository.addFocusSessionForToday(randomSeconds, randomTag);
      // The _sessionSubscription will automatically update _todaySessions and _statusMessage
      // due to the real-time listener.
    } catch (e) {
      setState(() {
        _statusMessage = 'Failed to add session: $e';
      });
    }
  }

  @override
  void dispose() {
    // IMPORTANT: Cancel the stream subscription when the widget is disposed
    // to prevent memory leaks and unnecessary network activity.
    _sessionSubscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Daily Focus Tracker'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              _statusMessage,
              style: const TextStyle(fontSize: 16, fontStyle: FontStyle.italic),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _addRandomFocusSession,
              child: const Text('Add New Focus Session'),
            ),
            const SizedBox(height: 20),
            Text(
              'Today\'s Sessions (${_todaySessions.length}):',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 10),
            Expanded(
              child: _todaySessions.isEmpty
                  ? const Center(child: Text('No sessions recorded for today yet.'))
                  : ListView.builder(
                      itemCount: _todaySessions.length,
                      itemBuilder: (context, index) {
                        final session = _todaySessions[index];
                        return Card(
                          margin: const EdgeInsets.symmetric(vertical: 8.0),
                          child: ListTile(
                            title: Text('${session.tag} - ${session.secondsSpend ~/ 60} min'),
                            subtitle: Text('Started: ${session.startTime.toLocal().toString().split('.')[0]}'),
                            // You could add more details or actions here, e.g., edit/delete
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
